### ISSUE TITLE
schedule meeting CTA button redirects to not found page

### ISSUE THREAD

**Issue by ridhof** [grikomsn/multiverse#322]
**Describe the bug**
clicking a schedule meeting CTA button redirects to a not found page.

**To Reproduce**
1. Go to [https://griko.id/](https://griko.id/)
2. Click on 'Schedule Meeting' (both Safari and Chrome browsers doesn't work)
3. See error

**Expected behavior**
Should be a way to schedule a meeting, like a form or redirect to google calendar or any calendar service providers.

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [chrome and safari]

**Comment by grikomsn** [comment]
Fixed!
